server {
    listen 80;
    server_name novatra;
    
    # 這裡必須是容器內的絕對路徑
    root /var/www/html/frontend; 
    index index.html index.php;

    location / {
        # 這一行很重要，它會自動尋找資料夾下的 index 檔案
        try_files $uri $uri/ /index.html;
    }

    location ~ \.php$ {
        # 這裡要跟 docker-compose 裡的服務名稱一致
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        # 這一行決定了 PHP 去哪裡抓檔案
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}