server {
    listen 80;
    server_name novatra;
    
    # 這裡必須是容器內的絕對路徑
    root /var/www/html/frontend/dist;
    index index.html index.php;

    # 處理 API：導向 Phalcon
    location /api {
        root /var/www/html/backend/public;
        try_files $uri $uri/ /index.php?_url=$uri&$args;
    }

    location /novatra/api/ {
        rewrite ^/novatra/api/(.*)$ /$1 break;
        
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
    }

    # 處理前端路由
    location / {
        # 它會自動尋找資料夾下的 index 檔案
        try_files $uri $uri/ /index.html;
    }

    # PHP 處理
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        # 這一行決定了 PHP 去哪裡抓檔案
        fastcgi_param SCRIPT_FILENAME /var/www/html/backend/public/index.php;
        fastcgi_param QUERY_STRING $query_string;
    }
}